### ISSUE TITLE
Scalability with a lot of elements

### ISSUE THREAD

**Issue by 9s-l-s9** [TomHumphries/InfiniteCanvasWhiteboard#1]
Great product :) 

Do you think it would be possible to re-create something like https://www.loom.com/share/e579c1642f9e4edea402d139cdbd5e94 
with your template? 😅 Or do you have an idea for a different approach? Mainly wondering about performance with a lot of elements. 

I am grateful for any kind of input :D

**Comment by IllustratedMan-code** [comment]
I implemented something using this template before, It can handle hundreds of elements pretty well. You could probably squeeze out more performance with webassembly if needed.

**Comment by TomHumphries** [comment]
To help with performance for lots of elements, you could try to render only things that are in view. It might be worth doing a quick test to check that the extra "is in view" check actually speeds up the draw time.

I imagine that the biggest performance hit will be when you're zoomed all the way out and everything is being drawn. For that you could try to detect which elements are too small to take up the width of a pixel and render them as a single point. You could potentially use nested 2D grids to determine the scale and position of elements. 

Perhaps there are techniques that can be applied from game engines for rendering detail at different distances / objects not in view?

**Comment by 9s-l-s9** [comment]
Thank you for your quick replies :) I've got some ideas out of them on how I am going to implement it
